---
parser: babel-eslint
parserOptions:
  ecmaVersion: 7
  sourceType: module
  ecmaFeatures:
    jsx: true
    modules: true
    experimentalObjectRestSpread: true
    allowImportExportEverywhere: true
plugins:
  - meteor
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:meteor/recommended
env:
  browser: true
  meteor: true
  es6: true
rules:
  import/no-extraneous-dependencies: 'off'
  import/prefer-default-export: 'off'
  no-unused-vars:
    - error
    - argsIgnorePattern: "^_"
      varsIgnorePattern: "^_"
      ignoreRestSiblings: true
  no-underscore-dangle: 'off'
  class-methods-use-this: 'off'
  meteor/no-session: 'off'
  object-shorthand:
    - error
    - always
    - avoidQuotes: false
  meteor/eventmap-params:
    - error
    - eventParamName: event
      templateInstanceParamName: instance
  meteor/template-names: 'off'
  meteor/audit-argument-checks: 'off'
  react/forbid-prop-types: 'off'
  react/prop-types: 'off'
  jsx-a11y/no-static-element-interactions: 'off'
settings:
  import/resolver: meteor
